name: instagram
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  video_player: ^2.10.0
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.2.0
  photo_manager: ^3.7.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/splashscreen_images/
    - assets/images/

# =======================
# Flutter Launcher Icons
# =======================
flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/appicon.png"
  image_path_ios: "assets/images/appicon.png"
  adaptive_icon_foreground: "assets/images/appicon.png" # Android only
