name: instagram
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  video_player: ^2.10.0
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.2.0
  photo_manager: ^3.7.1
  shared_preferences: ^2.5.3
  qr_flutter: ^4.1.0
  share_plus: ^12.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  gal: ^2.3.2
  visibility_detector: ^0.4.0+2
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.1
  camera: ^0.11.2
  vector_math: ^2.2.0
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splashscreen_images/
    - assets/images/
    - assets/videos/
    - assets/fonts/
    - assets/Icons/


  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.otf

# =======================
# Flutter Launcher Icons
# =======================
flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/appicon.png"
  image_path_ios: "assets/images/appicon.png"
  adaptive_icon_foreground: "assets/images/appicon.png" # Android only
